import type { Metadata } from "next";
import { Anton, Outfit } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout/Layout";
import { ShoppingCartContextProvider } from "@/context/ShoppingCartContext";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-base",
});

const anton = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-title",
});

export const metadata: Metadata = {
  title: "SHOP.CO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${anton.variable} antialiased`}>
        <ShoppingCartContextProvider>
          <Layout>{children}</Layout>
        </ShoppingCartContextProvider>
      </body>
    </html>
  );
}
